# Generated by Django 5.0 on 2024-01-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_producttype_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='producttype',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stock.producttype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='productlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlist', to='stock.product'),
        ),
    ]
