# Generated by Django 5.0 on 2024-01-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_producttype_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='featured_product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='productlist',
        ),
    ]
