# Generated by Django 5.0 on 2024-01-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='productlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlist', to='stock.product'),
        ),
    ]
