# Generated by Django 5.0 on 2024-01-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_producttype_featured_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='productlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlist', to='stock.product'),
        ),
    ]
