# Generated by Django 5.0.1 on 2024-01-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_property_brand_alter_property_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='productlist',
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productslist', to='stock.purchase'),
        ),
    ]
