# Generated by Django 5.0.1 on 2024-01-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_purchase_user_sale_user_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='featured_product',
        ),
    ]
